-name: RoboShop Project - Frontend
 hosts: all
 become: true
 tasks:
   - name: Install Nginx
     ansible.builtin.dnf:
       name: nginx
       state: installed

   - name: Copy Roboshop Configuration
     ansible.builtin.copy:
       src: nginx-roboshop.conf
       dest: /etc/nginx/default.d/roboshop.conf


