- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.prashdevops.online -uroot -pRoboShop@1 < /app/schema/{{component}}.sql
