groups:
  - name: ec2
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Instance Down

      - alert: CPUUsageHigh
        expr: sd
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: CPU Usage High
          description: {{ $labels.instance }}